version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  aied: #name of the second service
    build: .
    environment:
      - MONGO_URI=mongodb://db:27017/mockup
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000" #specify ports forewarding
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo
    environment:
      - MONGODB_USER=xiwa03
      - MONGODB_PASS=admin
      - MONGO_INITDB_DATABASE=mockup
      - MONGO_DATA_DIR=/data/db
    ports:
      - "27027:27017"
    volumes:
      - ./data/db:/data/db
    command: mongod --bind_ip_all --smallfiles --logpath=/dev/null # --quiet
    #command: [mongod, --dbpath, /data/db]
#volumes:
#  db:

